language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE carstest;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: fpoaTJw47tBFZbWL9KA/eLbkdgL2i/N6Q1LyIIQ6EKfr6Dq8AHMgjtXVSuOxAyzLG4huQDu7j6SP/r3P3VaONSLKHD5H6UWOmIdgm8XIr6lQwOOCAMUVcGXFfHpsbtI+gh8ydEr1bh/4uEp0GlxICR8ZdwgndUdnJbwLKpqvQGcDF9xmvw0yb9aHZhzxrnhUoKTCt3uapSH4cJTCRKMe/S8zeCVihWuGtPADcYZsNWRq1xMoa60SafZurHq0wyBaw+zYLtONKLwimETBHyfQ2LTV2Cuzvt5F84aUR46lfTCxifXE524b5n3ddQ9Lnx8J7X9JinGUBgD6ZCapYFkyo51jOM3DXk7ZUxzuPL3Kvu43fAWkKD+0L6YhYLEgTFlv8RU6TmYOEfZrEtqwBWqn1aw8F2p/G4gseYshIAFALSWncn7d3SP+kN3vzMc5PuXl66EqwnbFZNpJfn8UuUC4p02sikHXDUY3xsrNpRxDMzlA79GUK2nu1ZpXXq/RbWwuT+xveqDFoWHH2T5hDr9V3hYnLeqwB2LVkucNZMUZFNqVIE/0B0rwm/O2QbkSi2B7/GcqJKUGv/EbDutbmMJmwSlrqndPkzbASoye6y0rhI3cN9b41xh0HyvV3QA4lmhyCzu5DniSRBPbD2Jn0RHP/SkucPHK6nxR00I68bfLFN4=
  app: byobjustin3313
  skip_cleanup: true
