language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE carstest;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: krmv6PGCko1dhkaJBK/6M63l0kS97l8jaT/LE+NBn/dt9caOgXQCcHO3sFmkmc+2z3qsIQMmWLHleOqniv2R5aFT2bgEbyko/up988L39+e7VbSXvjpQq4Y0AlO4vnzUW70v9LiJbvBsaTpPvsZxyan3p44AP00Zf8XDowj0vg/MCPDBaU3usugh3GYGFDZ6JeonDYO4zkwDCmSAguSJbF2IPgqpDHvSjydzvYHxYRELNntbjOWpVB3kH3INAV6FxKaFdW8z6UiJK1PIdPegxQ405CWUE402tjpzcgUxmz7ZEJ45911Z8KX0cFCJJh6aHqgArLCL0ikNlzcnNrFjDetcvnxWI0kyi5dxWrOD0Gu/fn0Y1rKkcFH1zjPLxOlTb+WRzUI4iOcS0BejJL9lUWK/yT2BrmBYezTC5x4COYjcu4f9Bmys2iv0qPXEFEBceBszczlVmz+j9EKz0xp4vUxDGi+7PWIn7ZirU34Tkxcdc7Gc95chhGRp7IzD7xXFmvxnHZt0pt4zbmV5mv5GMZp2M7FAtpdI1MpPkEYpByynH2HGr36SGWmFBh7IDTiPzTffR3GI4bd2nOuWEEsSZgncSLkToDWh+cwImOZbBYPYhWjkQTWmLjajADxWud95MDUmkymTrXJ9oVOIWeAdWNkZiePxvX81lvB39ZSD3bk=
  app: byobjustin3313
  skip_cleanup: true
